[package]
name = "bnk"
version = "0.1.0"
edition = "2021"

[features]
default = []
profiling = ["dep:puffin"]

[dependencies]
thiserror.workspace = true

nom = "7.1.3"
puffin = { version = "0.18", optional = true }
