[package]
name = "rodio_wem"
version = "0.1.0"
edition = "2021"

[dependencies]
lewton = "0.10.2"
nom = "7.1.1"
rodio = { version = "0.15.0", default-features = false, features = ["vorbis"] }
thiserror = "1.0.31"
