[package]
name = "rockysmithereens_parser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
psarc = { path = "../psarc" }
rodio_wem = { path = "../rodio_wem" }
quick-xml = { version = "0.23.0", features = ["serialize"] }
serde = { version = "1.0.138", features = ["derive"] }
serde_json = "1.0.82"
thiserror = "1.0.31"
