[package]
name = "rockysmithereens_parser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
psarc = { path = "../psarc" }
quick-xml = { version = "0.23.0", features = ["serialize"] }
serde = { version = "1.0.137", features = ["derive"] }
serde_json = "1.0.81"
thiserror = "1.0.31"
