[package]
name = "rockysmithereens"
version = "0.1.0"
edition = "2021"
default-run = "rockysmithereens"

[dependencies]
rodio_wem = { path = "../crates/rodio_wem" }
rockysmithereens_parser = { path = "../crates/rockysmithereens_parser" }
anyhow = "1.0.58"
bevy = { version = "0.7.0", default-features = false, features = ["render", "bevy_audio", "bevy_winit", "x11"] }
bevy_egui = "0.14.0"
clap = { version = "3.2.8", features = ["derive"] }
rfd = "0.9.1"
lazy_static = "1.4.0"
