[package]
name = "rockysmithereens"
version = "0.1.0"
edition = "2021"
default-run = "rockysmithereens"

[dependencies]
rodio_wem = { path = "../crates/rodio_wem", features = ["profile-with-tracing"] }
rockysmithereens_parser = { path = "../crates/rockysmithereens_parser", features = ["profile-with-tracing"] }

anyhow = "1.0.58"
bevy = { version = "0.7.0", default-features = false, features = ["render", "bevy_audio", "bevy_winit", "x11", "dds"] }
bevy_egui = "0.14.0"
clap = { version = "3.2.8", features = ["derive"] }
rfd = "0.9.1"
lazy_static = "1.4.0"
rodio = { version = "0.15.0", default-features = false }
profiling = "1.0.6"
bevy_puffin = { version = "0.1.0", optional = true }
puffin_egui = { version = "0.16.0", optional = true }

[features]
profile = ["profiling/profile-with-tracing", "bevy_puffin", "puffin_egui"]

[target.'cfg(target_arch = "wasm32")'.dependencies]
tracing-wasm = "0.2.1"
console_error_panic_hook = "0.1.7"
