[package]
name = "rockysmithereens"
version = "0.1.0"
edition = "2021"
default-run = "rockysmithereens"

[dependencies]
rodio_wem = { path = "../crates/rodio_wem", features = ["profile-with-tracing"] }
rockysmithereens_parser = { path = "../crates/rockysmithereens_parser", features = ["profile-with-tracing"] }

pixel-game-lib = { version = "0.4.0", default-features = false, features = ["embedded-assets", "default-font"] }
miette = "5.10.0"
taffy = "0.3.18"
tokio = { version = "1.34.0", features = ["rt", "full"] }
rfd = "0.12.1"
