[package]
name = "psarc_extract"
version = "0.1.0"
edition = "2021"

[dependencies]
psarc = { path = "../../crates/psarc" }
rodio_wem = { path = "../../crates/rodio_wem" }

anyhow = "1.0.75"
clap = { version = "3.2.25", features = ["derive"] }
env_logger = "0.9.3"
log = "0.4.20"
