[package]
name = "psarc_extract"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.58"
clap = { version = "3.2.8", features = ["derive"] }
env_logger = "0.9.0"
log = "0.4.17"
psarc = { path = "../../crates/psarc" }
rodio_wem = { path = "../../crates/rodio_wem" }
