[package]
name = "psarc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "7.1.1"
semver = "1.0.10"
thiserror = "1.0.31"
aes = "0.8.1"
cfb-mode = "0.8.1"
hex-literal = "0.3.4"
flate2 = "1.0.24"
log = "0.4.17"
